### ISSUE TITLE
Auth.refreshSession does not work inside API/getServerSideProps

### ISSUE THREAD

**Issue by 413n** [supabase-community/supabase-auth-helpers#83]
_Maybe this issue could be solved with #62_

I wanted to have a **NextJS** `API` or page with `getServerSideProps` that will refresh the session to get the latest `user_meta_data` of the authenticated user.

I was doing it client side now but sometimes it was failing because I needed to wait a little bit for a trigger to finish before fetching the new user_meta_data, but I thought anyway it was better to do this server side so I created an `API` for that. **(Any suggestion for a best solution is accepted)**.

I then tried using the `supabase.auth.refreshSession()` both on an API and on a getServerSideProps but it is failing with the following error:
```
Refreshed user:  {
  data: null,
  user: null,
  error: Error: No current session.
      at SupabaseAuthClient.eval (webpack-internal:///../../node_modules/.pnpm/@supabase+gotrue-js@1.22.12/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:557:27)
      at Generator.next (<anonymous>)
      at eval (webpack-internal:///../../node_modules/.pnpm/@supabase+gotrue-js@1.22.12/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:8:71)
      at new Promise (<anonymous>)
      at __awaiter (webpack-internal:///../../node_modules/.pnpm/@supabase+gotrue-js@1.22.12/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:4:12)
      at SupabaseAuthClient._callRefreshToken (webpack-internal:///../../node_modules/.pnpm/@supabase+gotrue-js@1.22.12/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:554:16) 
      at SupabaseAuthClient.eval (webpack-internal:///../../node_modules/.pnpm/@supabase+gotrue-js@1.22.12/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:242:46)
      at Generator.next (<anonymous>)
      at eval (webpack-internal:///../../node_modules/.pnpm/@supabase+gotrue-js@1.22.12/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:8:71)
      at new Promise (<anonymous>)
}
Error while refreshing the user data:  Error: No current session.
    at SupabaseAuthClient.eval (webpack-internal:///../../node_modules/.pnpm/@supabase+gotrue-js@1.22.12/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:557:27)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///../../node_modules/.pnpm/@supabase+gotrue-js@1.22.12/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:8:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///../../node_modules/.pnpm/@supabase+gotrue-js@1.22.12/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:4:12)
    at SupabaseAuthClient._callRefreshToken (webpack-internal:///../../node_modules/.pnpm/@supabase+gotrue-js@1.22.12/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:554:16)   
    at SupabaseAuthClient.eval (webpack-internal:///../../node_modules/.pnpm/@supabase+gotrue-js@1.22.12/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:242:46)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///../../node_modules/.pnpm/@supabase+gotrue-js@1.22.12/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:8:71)
    at new Promise (<anonymous>)
```

API code:
```javascript
import {
  supabaseServerClient,
  withAuthRequired
} from '@supabase/auth-helpers-nextjs';

export default withAuthRequired(async (req, res) => {
  let { returnTo = '/' } = req.query;
  returnTo = Array.isArray(returnTo) ? returnTo[0] : returnTo;
  returnTo = returnTo.charAt(0) === '/' ? returnTo : `/${returnTo}`;

  // Refreshes the user data
  const refreshedUser = await supabaseServerClient({
    req
  }).auth.refreshSession();

  console.error('Refreshed user: ', refreshedUser);

  if (refreshedUser.error) {
    console.error(
      'Error while refreshing the user data: ',
      refreshedUser.error
    );
  }

  res.status(200).json({ refreshedUser });
  // res.redirect(returnTo as string);
});
```

Basically same code for the `getServerSideProps`:
```javascript
export const getServerSideProps = withAuthRequired({
  redirectTo: '/',
  async getServerSideProps(ctx) {
    // Refreshes the user data
    const refreshedUser = await supabaseServerClient(ctx).auth.refreshSession();

    console.error('Refreshed user: ', refreshedUser);

    if (refreshedUser.error) {
      console.error(
        'Error while refreshing the user data: ',
        refreshedUser.error
      );
    }
ab
    return {
      redirect: {
        destination: '/',
        permanent: false
      }
    };
  }
});
```

Watching in the lib code it seems that here (https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L671) the `refresh_token` is empty so the `currentSession` loaded server side does not have the `refreshToken` but has the `accessToken` set because it _does not_ fail here (https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L336).

I tried using the `auth.api` directly to refresh the accessToken:
```javascript
  const refreshedUser = await supabaseServerClient({
    req,
  }).auth.api.refreshAccessToken(req.cookies["sb-refresh-token"]);
```
but it's not working either.
The refresh token is "refreshed" but apparently not saved because the next time you access the same page the `refresh token` is invalid and you get an error.

**Comment by thorwebdev** [comment]
You can use the `getUser` method server-side: https://github.com/supabase-community/supabase-auth-helpers/blob/main/src/nextjs/README.md#server-side-rendering-ssr---withauthrequired

**Comment by thorwebdev** [comment]
Alternatively, from version `1.4.0` onward you will be able to call `supabase.auth.refreshSession()` client-side to refresh the JWT & user object throughout.

**Comment by 413n** [comment]
@thorwebdev I'll use the new function has soon as available then! Thanks!
